language: node_js
node_js:
  - '6'
  - '5'
  - '4'
before_script:
  - $(npm bin)/tsc --version
script:
  - npm run build
  - npm run lint
  - npm test
after_success:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
cache:
  directories:
    - node_modules
sudo: false
