language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "iojs"
script:
  - npm run build
  - npm test
  - npm run lint
after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
cache:
  directories:
    - node_modules
sudo: false
